export const nodes = [
  {
    id: "1",
    type: "customCard",
    position: { x: 570, y: 30 },
    data: { label: "Arrays & Hashing", progress: 80 },
  },
  {
    id: "2",
    type: "customCard",
    position: { x: 420, y: 120 },
    data: { label: "Two Pointer", progress: 75 },
  },
  {
    id: "3",
    type: "customCard",
    position: { x: 720, y: 120 },
    data: { label: "Stack", progress: 70 },
  },

  {
    id: "4",
    type: "customCard",
    position: { x: 220, y: 220 },
    data: { label: "Binary Search", progress: 65 },
  },
  {
    id: "5",
    type: "customCard",
    position: { x: 420, y: 220 },
    data: { label: "Sliding Window", progress: 60 },
  },

  {
    id: "6",
    type: "customCard",
    position: { x: 620, y: 220 },
    data: { label: "Linked List", progress: 55 },
  },
  {
    id: "7",
    type: "customCard",
    position: { x: 370, y: 310 },
    data: { label: "Trees", progress: 50 },
  },
  {
    id: "8",
    type: "customCard",
    position: { x: 170, y: 400 },
    data: { label: "Tries", progress: 45 },
  },
  {
    id: "9",
    type: "customCard",
    position: { x: 270, y: 500 },
    data: { label: "Heap / Priority Queue", progress: 40 },
  },
  {
    id: "10",
    type: "customCard",
    position: { x: 770, y: 400 },
    data: { label: "Backtracking", progress: 35 },
  },
  {
    id: "11",
    type: "customCard",
    position: { x: 670, y: 500 },
    data: { label: "Graph", progress: 30 },
  },
  {
    id: "12",
    type: "customCard",
    position: { x: 870, y: 500 },
    data: { label: "1D DP", progress: 25 },
  },
  {
    id: "13",
    type: "customCard",
    position: { x: 770, y: 620 },
    data: { label: "2D DP", progress: 20 },
  },
  {
    id: "14",
    type: "customCard",
    position: { x: 170, y: 620 },
    data: { label: "Greedy", progress: 15 },
  },
  {
    id: "15",
    type: "customCard",
    position: { x: 370, y: 620 },
    data: { label: "Advanced Graphs", progress: 10 },
  },
];


export const edges = [
  {
    id: "1-2",
    source: "1",
    target: "2",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "1-3",
    source: "1",
    target: "3",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "2-4",
    source: "2",
    target: "4",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "2-5",
    source: "2",
    target: "5",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "2-6",
    source: "2",
    target: "6",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "4-7",
    source: "4",
    target: "7",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "6-7",
    source: "6",
    target: "7",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "7-8",
    source: "7",
    target: "8",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "7-9",
    source: "7",
    target: "9",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "7-10",
    source: "7",
    target: "10",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "9-13",
    source: "9",
    target: "15",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "9-14",
    source: "9",
    target: "14",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "10-11",
    source: "10",
    target: "11",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "10-12",
    source: "10",
    target: "12",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "11-13",
    source: "11",
    target: "13",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "12-13",
    source: "12",
    target: "13",
    type: "default",
    MarkerType: "arrowclosed",
  },
  {
    id: "11-15",
    source: "11",
    target: "15",
    type: "default",
    MarkerType: "arrowclosed",
  },
];