export type TaskType = "assignment" | "application" | "drive" | "orientation" | "assessment deadline"

export interface ScheduleItem {
  id: string
  title: string
  type: TaskType
  dueDate: Date
  status: "pending" | "in-progress" | "completed"
  notes?: string
  description: string // Added description field
}

export const scheduleItems: ScheduleItem[] = [
  {
    id: "1",
    title: "DSA Assignment 4",
    type: "assignment",
    dueDate: new Date("2025-07-01"),
    status: "in-progress",
    notes: "Focus on dynamic programming section",
    description: "Complete the fourth assignment on Dynamic Programming for the Data Structures and Algorithms course.",
  },
  {
    id: "2",
    title: "Apply to Microsoft SWE Internship",
    type: "application",
    dueDate: new Date("2025-07-02"),
    status: "pending",
    notes: "Include resume with latest project",
    description: "Submit application for the Software Engineering Intern position at Microsoft, including an updated resume and latest project details.",
  },
  {
    id: "3",
    title: "AI Research Paper Review",
    type: "assignment",
    dueDate: new Date("2025-07-03"),
    status: "pending",
    notes: "Summarize key findings and critique methods",
    description: "Review and summarize a research paper on Artificial Intelligence, focusing on key findings and critiquing the methods used.",
  },
  {
    id: "4",
    title: "Apply to Google STEP Internship",
    type: "application",
    dueDate: new Date("2025-07-03"),
    status: "pending",
    description: "Submit application for the Student Training in Engineering Program (STEP) internship at Google.",
  },
  {
    id: "5",
    title: "Operating Systems Project",
    type: "assignment",
    dueDate: new Date("2025-07-04"),
    status: "in-progress",
    notes: "Implement process scheduling simulation",
    description: "Develop a project simulating process scheduling algorithms for the Operating Systems course.",
  },
  {
    id: "6",
    title: "Revise Linked List Questions",
    type: "assignment",
    dueDate: new Date("2025-07-05"),
    status: "in-progress",
    notes: "Focus on edge case handling",
    description: "Review and revise solutions to linked list problems, focusing on edge case handling.",
  },
  {
    id: "7",
    title: "Submit Resume for StartupX",
    type: "application",
    dueDate: new Date("2025-07-06"),
    status: "completed",
    notes: "Add AI project from last semester",
    description: "Submit an updated resume to StartupX, including the AI project from the previous semester.",
  },
  {
    id: "8",
    title: "Mock Interview with Career Services",
    type: "orientation",
    dueDate: new Date("2025-07-07"),
    status: "pending",
    description: "Schedule a mock interview with Career Services to prepare for upcoming job interviews.",
  },
  {
    id: "9",
    title: "Revise OOP Concepts",
    type: "assignment",
    dueDate: new Date("2025-07-08"),
    status: "pending",
    description: "Review and revise understanding of Object-Oriented Programming concepts.",
  },
  {
    id: "10",
    title: "Apply to Salesforce Intern Role",
    type: "application",
    dueDate: new Date("2025-07-09"),
    status: "in-progress",
    description: "Submit application for the Intern position at Salesforce.",
  },
  {
    id: "11",
    title: "Company ABC Hiring Drive",
    type: "drive",
    dueDate: new Date("2025-07-10"),
    status: "pending",
    notes: "Complete test before 5 PM",
    description: "Participate in the hiring drive for Company ABC, ensuring to complete the test before the deadline.",
  },
  {
    id: "12",
    title: "Review OS Memory Management",
    type: "assignment",
    dueDate: new Date("2025-07-11"),
    status: "in-progress",
    description: "Review and study the concepts of Memory Management in Operating Systems.",
  },
  {
    id: "13",
    title: "Orientation Meeting with Tech Club",
    type: "orientation",
    dueDate: new Date("2025-07-12"),
    status: "pending",
    description: "Attend the orientation meeting with the Tech Club to learn about upcoming events and opportunities.",
  },
  {
    id: "14",
    title: "Assessment Deadline: Java Basics",
    type: "assessment deadline",
    dueDate: new Date("2025-07-13"),
    status: "in-progress",
    notes: "Includes loops and arrays section",
    description: "Complete the assessment on Java Basics, covering topics such as loops and arrays.",
  },
  {
    id: "15",
    title: "Networking Fundamentals Recap",
    type: "assignment",
    dueDate: new Date("2025-07-14"),
    status: "pending",
    description: "Review and recap the fundamentals of Networking.",
  },
  {
    id: "16",
    title: "Submit Application to Tesla Internship",
    type: "application",
    dueDate: new Date("2025-07-15"),
    status: "completed",
    description: "Submit application for the Intern position at Tesla.",
  },
  {
    id: "17",
    title: "Practice SQL Queries",
    type: "assignment",
    dueDate: new Date("2025-07-16"),
    status: "in-progress",
    notes: "Practice joins and subqueries",
    description: "Practice writing SQL queries, focusing on joins and subqueries.",
  },
  {
    id: "18",
    title: "Attend Amazon SDE Info Session",
    type: "orientation",
    dueDate: new Date("2025-07-17"),
    status: "pending",
    description: "Attend the information session for Software Development Engineer positions at Amazon.",
  },
  {
    id: "19",
    title: "Assessment Deadline: Algorithms Quiz",
    type: "assessment deadline",
    dueDate: new Date("2025-07-17"),
    status: "pending",
    description: "Complete the assessment on Algorithms, including a quiz.",
  },
  {
    id: "20",
    title: "Company DEF Drive Coding Round",
    type: "drive",
    dueDate: new Date("2025-07-18"),
    status: "pending",
    description: "Participate in the coding round for Company DEF's hiring drive.",
  },
  {
    id: "21",
    title: "Write Summary for ML Paper",
    type: "assignment",
    dueDate: new Date("2025-07-19"),
    status: "pending",
    description: "Write a summary of a research paper on Machine Learning.",
  },
  {
    id: "22",
    title: "Submit Application to Adobe",
    type: "application",
    dueDate: new Date("2025-07-20"),
    status: "in-progress",
    description: "Submit application for the Intern position at Adobe.",
  },
  {
    id: "23",
    title: "Orientation: Project Kickoff Meeting",
    type: "orientation",
    dueDate: new Date("2025-07-21"),
    status: "pending",
    description: "Attend the project kickoff meeting for the new project orientation.",
  },
  {
    id: "24",
    title: "Assessment Deadline: React Basics",
    type: "assessment deadline",
    dueDate: new Date("2025-07-22"),
    status: "pending",
    notes: "Covers hooks and components",
    description: "Complete the assessment on React Basics, covering topics such as hooks and components.",
  },
  {
    id: "25",
    title: "System Design Reading",
    type: "assignment",
    dueDate: new Date("2025-07-23"),
    status: "in-progress",
    notes: "Scalability and caching",
    description: "Read and study system design concepts, focusing on scalability and caching.",
  }
]

